# Generated by Django 5.0.6 on 2024-05-11 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tariff",
            fields=[
                ("tariff_id", models.AutoField(primary_key=True, serialize=False)),
                ("tariff_value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("action_id", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PayrollReport",
            fields=[
                ("report_id", models.AutoField(primary_key=True, serialize=False)),
                ("period", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=100)),
                ("report_content", models.TextField()),
                (
                    "revenue_volume",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "shipment_volume",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("tariff_id", models.IntegerField(blank=True, null=True)),
                ("time_at_work", models.DurationField(blank=True, null=True)),
                ("action_id", models.IntegerField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infom.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaxesReport",
            fields=[
                ("report_id", models.AutoField(primary_key=True, serialize=False)),
                ("period", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=100)),
                ("report_content", models.TextField()),
                (
                    "revenue_volume",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "shipment_volume",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("tariff_id", models.IntegerField(blank=True, null=True)),
                ("time_at_work", models.DurationField(blank=True, null=True)),
                ("action_id", models.IntegerField(blank=True, null=True)),
                (
                    "income_tax_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "contribution_tax_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infom.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShipmentRevenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_id", models.IntegerField()),
                (
                    "revenue_volume",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "shipment_volume",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("date", models.DateField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="infom.employee"
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "action_id", "date")},
            },
        ),
        migrations.CreateModel(
            name="WorkTimeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("date", models.DateField()),
                ("time_at_work", models.DurationField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="infom.employee"
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "start_time", "end_time")},
            },
        ),
    ]
